WIP: Feature/symfony implementation
mobilejazz/harmony-php pull request #46
Opened 2022-03-23 16:52 UTC by Alex-DA

2022-11-21 06:59 UTC, joselufo commented
@Alex-DA I converted it to Draft as the title said WIP.

2022-12-08 14:26 UTC, urijp requested changes

2022-12-08 14:26 UTC, urijp commented on sample/src/tests/integration/Product/Domain/Interactor/RawSqlProductInteractorsTest.php
> +    $dataSourceMapper = new DataSourceMapper(
Same as before, like you call productProvider some lines below, here is $productDatasource

2022-12-08 14:26 UTC, urijp commented on sample/src/tests/unit/Product/Domain/Interactor/ProductInteractorsTest.php
> +    $productSaved = $this->putProduct($productProvider, $product);
These three lines are repeated a lot, could we move them to a new method?

2022-12-08 14:26 UTC, urijp commented on sample/src/tests/unit/Product/Domain/Interactor/ProductInteractorsTest.php
> +    $productUpdated = $this->putProduct($productProvider, $productWithChange);
updatedProduct

2022-12-08 14:26 UTC, urijp commented on sample/src/tests/unit/Product/Domain/Interactor/ProductInteractorsTest.php
> +    $productWithChange = new Product(
editedProduct

2022-12-08 14:26 UTC, urijp commented on sample/src/tests/unit/Product/Domain/Interactor/ProductInteractorsTest.php
> +    $productGot = $productProvider->provideGetInteractor()($queryGet);
$resultingProduct maybe?

2022-12-08 14:26 UTC, urijp commented on sample/src/tests/unit/Product/Domain/Interactor/ProductInteractorsTest.php
> +    $productsSaved = $this->putProducts($productProvider, $products);
$savedProducts

2022-12-08 16:20 UTC, Alex-DA commented on core/src/Domain/Interactor/PutAllInteractor.php
> +   * @param Query|null     $query
@urijp prettier.

2022-12-08 16:35 UTC, Alex-DA commented on sample/src/app/Application/ProductIndexAction.php
> +    $query = new AllQuery();
@orioljp the default one is VoidQuery in `core/src/Domain/Interactor/PutAllInteractor.php`

2022-12-08 17:01 UTC, Alex-DA commented on sample/src/app/Application/ProductIndexAction.php
> +    $query = new AllQuery();
Thanks for your comment, I found a mismatch on GetAllInteractor, I changed the default query from AllQuery to VoidQuery.

2022-12-08 18:11 UTC, urijp commented on sample/src/app/Application/ProductIndexAction.php
> +    $query = new AllQuery();
But what's the default behaviour? Here we want to put all with a put all method, that should be the default behaviour so no query should be needed.

2022-12-08 18:13 UTC, urijp approved these changes

2022-12-09 07:43 UTC, Alex-DA commented on sample/src/app/Application/ProductIndexAction.php
> +    $query = new AllQuery();
@urijp I will create a new task to follow-up this case, as I see that we have many strategies in the other Harmony libs, and I prefer to align all the same.

2022-12-13 08:53 UTC, Alex-DA commented on core/src/Helper/Random.php
> +
@magarzon Is not a Harmony Code Style, but my personal Code Style 😝
The reason is to make work easier when we are debugging with XDebug.

Normally when you are debugging a result from a function you need to modify the code first to get the result in a variable, add a breakpoint and see the value, and finally revert the changes.

Using always an intermediate variable before returns, you only need to add a breakpoint to the `return` line and continue working.

I know that in other languages the debugger allows you to stop in the last line and see the result before the return, but is not the case with XDebug yet (at least, last time that I checked).

2022-12-13 10:04 UTC, merged