BACKEND-6785 :: Feature :: Add key and composed query to delete on RawSqlDataSource
mobilejazz/harmony-php pull request #54
Opened 2022-08-16 14:15 UTC by lucianosantana

**Merge / Pull request information:**

Adds key and composed query to delete on RawSqlDataSource

* Asana task link:https://app.asana.com/0/1109863238977521/1202798243156785/f

2022-08-16 14:19 UTC, lucianosantana commented
I've also used this PR to fix a typo on the KeyQuery

2022-08-16 14:50 UTC, doup requested changes
You're repeating the same logic for `deleteById`, `deleteByKey` & `deleteComposed`. Looks like you can create a `getDeleteFactory` that runs the soft delete if logic and returns the factory with some basic configuration, and then add the specific `where` clause. 

In `deleteById/Key`, the `where` clause in the two branches of the soft delete is the same.

It could be something like this?

```php
  public function deleteById(mixed $value): SqlQuery {
    return $this
        ->getDeleteFactory();
        ->where(field($this->schema->getIdColumn())->eq($value))
        ->compile();
  }

  public function deleteByKey(mixed $value): SqlQuery {
    return $this
        ->getDeleteFactory();
        ->where(field($this->schema->getKeyColumn())->eq($value))
        ->compile();
  }

  public function deleteComposed(ComposedQuery $composed): SqlQuery {
    $factory = this->getDeleteFactory();
    
    return $factory
        ->addWhereConditions($composed, $factory)
        ->compile();
  }
```

2022-08-16 15:01 UTC, lucianosantana commented
I've  applied your suggestions @doup

2022-08-16 16:15 UTC, doup approved these changes

2022-08-16 16:36 UTC, orioljp approved these changes

2022-08-17 06:42 UTC, joselufo approved these changes

2022-08-17 09:18 UTC, merged