BACKEND-0957 :: Feature :: Harmony PHP | WhereQuery improvement
mobilejazz/harmony-php pull request #64
Opened 2022-12-28 20:40 UTC by urijp

**Asana task link**:
[https://app.asana.com/0/0/1202280093660957/f](https://app.asana.com/0/0/1202280093660957/f)

**Merge / Pull request information:**
Adding where criterias to WhereQuery to extend the current behaviour to add more types of conditions using the RawSqlDataSource

2022-12-30 08:06 UTC, joselufo approved these changes

2023-01-03 07:55 UTC, Alex-DA requested changes

2023-01-03 07:55 UTC, Alex-DA commented on core/src/Repository/Query/WhereCriteria.php
> +class WhereCriteria {
@orioljp in PHP 8.1 we don't need to use psalm-immutable anymore.
Instead add `readonly` to each property.

2023-01-04 15:28 UTC, lucianosantana approved these changes

2023-01-04 16:19 UTC, Alex-DA approved these changes

2023-01-04 16:19 UTC, merged

2023-01-05 00:06 UTC, magarzon reviewed
All ok